### ISSUE TITLE
FodyWeavers.xml erased on update

### ISSUE THREAD

**Issue by benjamin-bader** [benjamin-bader/stiletto#10]
Before update:

```
<FodyWeavers>
  <Stiletto />
</FodyWeavers>
```

After update:

```
<FodyWeavers>
</FodyWeavers>
```

**Comment by GiroSA** [comment]
It is 2018 and this is still happening. I have been bitten by this several times. I will hopefully remember now to check the file after an update.

**Comment by SimonCropp** [comment]
stop including these files in the nuget https://github.com/benjamin-bader/stiletto/tree/master/NuGet/Stiletto.Fody

people can then manage the xml manually
