### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by SimonCropp** [benjamin-bader/stiletto#32]
Fody Version 2 is out and you will need to do an update for your addin to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency range for Fody to be at least 2.0

 Please ping me if u need help

**Comment by benjamin-bader** [comment]
Hi Simon,

Thanks for the notice.  This project is more-or-less abandonware - it hasn't seen any development for years now.  I would be surprised if anyone uses it; if someone does and has interest, I'd gladly hand it over.  I won't be doing any further work on it myself.

**Comment by marcosrocha85** [comment]
@benjamin-bader , do you know any project which is like yours? I mean, I feel very comfortable to develop DI with Android, but I need a complement to use with Ninject on C#.

**Comment by benjamin-bader** [comment]
Hi Marcos,

I'm not sure what people use with Xamarin these days; I haven't done any mobile C# work in 4-5 years, it seems, and so am pretty out-of-touch.  Last time I checked, TinyIOC was popular but unsuited to the kind of application architectures I was working with.

If you're not targeting iOS, I _think_ ninject should work fine - iOS, with its restrictions on runtime codegen, is the limiting factor for most Xamarin DI frameworks.

**Comment by benjamin-bader** [comment]
A quick Google search seems to indicate that the Unity container is officially recommended by Xamarin/MSFT: https://developer.xamarin.com/guides/xamarin-forms/enterprise-application-patterns/dependency-injection/

I've never used it and can't vouch for it, but it would be a worthwhile topic to investigate.

**Comment by SimonCropp** [comment]
Sorry i dont have capacity to take this over. Perhaps add a note in the readme saying “no longer being actively developed”

**Comment by benjamin-bader** [comment]
Sounds like a fine idea!
